[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalcdapp = "A4jSUp4vSqH6KVrFXWvY23f1Cc1wMfXntKCqxN4MEfgj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
